### ISSUE TITLE
Azure pipeline fails to run 

### ISSUE THREAD

**Issue by samerzughul** [marceloavf/digitalocean-tools-vsts#10]
## Bug Report

**Describe the bug**

Azure pipeline is failing to start when i am using the upload task because both tasks have the same name.

**To Reproduce**

1. normal upload task

```shell
Job Job: Step task reference is invalid. The task name DigitalOcean is ambiguous. Specify one of the following identifiers to resolve the ambiguity: marcelo-formentao.digitalocean-tools.digital-ocean-spaces-upload-task.DigitalOcean, marcelo-formentao.digitalocean-tools.digital-ocean-spaces-delete-task.DigitalOcean
```

**Expected behavior**

the pipeline to work

**Enviroment**

* Service: VSTS
* Agent: Hosted
* OS: Ubuntu

**Comment by marceloavf** [comment]
Thanks for the report @samerzughul 

Are you using .yml for pipeline configuration?

**Comment by samerzughul** [comment]
yes
and here is the task

   - task: DigitalOcean@0
     displayName: Upload
     inputs:
       digitalCredentials: 'digitaloceanspace'
       digitalRegion: '$(BucketRegion)'
       digitalBucket: '$(BucketName)'
       digitalGlobExpressions: |
         **/*.zip
         *.zip
       digitalTargetFolder: 'adapters'

**Comment by marceloavf** [comment]
Try to use like this and see if it work please:

```diff
+task: marcelo-formentao.digitalocean-tools.digital-ocean-spaces-upload-task.DigitalOcean@0
-task: DigitalOcean@0
displayName: Upload
inputs:
digitalCredentials: 'digitaloceanspace'
digitalRegion: '$(BucketRegion)'
digitalBucket: '$(BucketName)'
digitalGlobExpressions: |
**/*.zip
*.zip
digitalTargetFolder: 'adapters'
```

**Comment by marceloavf** [comment]
@samerzughul Would love to hear your feedback here!
