### ISSUE TITLE
Upload performance improvement

### ISSUE THREAD

**Issue by trinhpham** [marceloavf/digitalocean-tools-vsts#12]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'd like to serve static pages that is generated by vuepress, hugo, etc.
However, the upload process is taking too long (around 9k files, 6GB in total), and it usually ends with pipeline timeout.

**Describe the solution you'd like**
Parallel upload to optimize the bandwidth. We might need to review the limits of DO Space.

**Describe alternatives you've considered**
I have no idea.

**Teachability, Documentation, Adoption, Migration Strategy**
I have no idea.

**Comment by marceloavf** [comment]
Hi @trinhpham, could you please describe your release environment? Do you use a hosted Linux, macOS, or Windows? Node version, etc.
Thanks.

**Comment by trinhpham** [comment]
I am running azure-devops-agent inside an ubuntu 16.04 Docker container (host is Linux also).
I didn't install NodeJS on that container, so  assume that the pipeline use the embedded node of azure-devops-agent.

**Comment by marceloavf** [comment]
I'm planning on releasing v1.0 in a couple of days with parallel upload and retry on error, but as I was searching about your problem and I came across these docs that may explain it a little:
https://www.digitalocean.com/docs/spaces/resources/performance-tips/
https://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html

If in v1.0 your problem continues, then we need to think about this implementation, using multi-part upload to increase performance and allow quick recovery from any network issue.

**Comment by marceloavf** [comment]
Hi @trinhpham 
The release v1 should be available now, you'll have some options to control parallel upload and more, hope it helps you.
If you still have a problem, feel free to reopen this issue.

**Comment by trinhpham** [comment]
Thank @marceloavf 
I switched to call s3cmd command while waiting for your update.
Just tested with v1 and faced an error (but not related to this issue).
I'll post another issue.

**Comment by trinhpham** [comment]
Posted #18
