### ISSUE TITLE
How do you use "install" command in azure dev ops pipeline?

### ISSUE THREAD

**Issue by MDUYN** [marceloavf/digitalocean-tools-vsts#47]
## How do you use DigitalOceanDoctlInstaller command in azure dev ops pipeline?

**Description**
How do use the install task in the azure devops pipeline? I tried the following:

```
- task: DigitalOceanDoctlInstaller@1
  name: Install doctl
```

**Comment by marceloavf** [comment]
Hey @MDUYN, just by calling it this way it should install it, have you tried using any command of `doctl` l after it?

**Comment by MDUYN** [comment]
When I try to run the task it gives me the following error: 
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/27549131/194748147-c079d676-96bb-4110-bac1-b01071def966.png">

I have installed the extension as can be seen here: 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/27549131/194748204-41fe425f-6ecd-4cb7-a003-00e83d6cbf23.png">

**Comment by marceloavf** [comment]
Could you try it with version @2, please? I think doctl was included in version 2 above.

Like this:
```
- task: DigitalOceanDoctlInstaller@2
  name: Install doctl
```

**Comment by MDUYN** [comment]
This works perfect, thanks!
